# Change these first
owner: abhishekakt1 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: npm-in
    url: https://npm.abhishekakt.tk
  - name: npm-plex
    url: https://npm-plex.abhishekakt.tk
  - name: npm-us
    url: https://npm-us.abhishekakt.tk
  - name: npm-nxcloud
    url: https://npm-hyd.abhishekakt.tk
    
  - name: wiki
    url: https://wiki.abhishekakt.tk
  - name: ArchiePlays
    url: https://archieplays.tk
  - name: AudioBooks
    url: https://audiobooks.abhishekakt.tk
  - name: Bazzar subtitle
    url: https://subtitle.abhishekakt.tk
  - name: DR Vaultwarden
    url: https://dr-pass.abhishekakt.tk
  - name: DR WIKI
    url: https://dr-wiki.abhishekakt.tk
  - name: Duplicati 
    url: https://duplicati.abhishekakt.tk
  - name: Graphana
    url: https://graph.abhishekakt.tk
  - name: Home Assistant
    url: https://ha.abhishekakt.tk
  - name: Jackett
    url: https://jackett.abhishekakt.tk
  - name: Jellyfin
    url: https://jellyfin.abhishekakt.tk
  - name: KASM
    url: https://kasm.abhishekakt.tk
  - name: KASM IN
    url: https://kasm-in.abhishekakt.tk
  - name: Kavita
    url: https://books.abhishekakt.tk
  - name: NXcloud
    url: https://cd.abhishekakt.tk
  - name: Plex
    url: https://plex.abhishekakt.tk/web/index.html
  - name: Prowlarr
    url: https://prowlarr.abhishekakt.tk
  - name: qBitTorrent
    url: https://tr.abhishekakt.tk
  - name: Radarr
    url: https://radarr.abhishekakt.tk
  - name: Sonarr
    url: https://sonarr.abhishekakt.tk
  - name: Tautulli
    url: https://agent.abhishekakt.tk/
  - name: ThePugs
    url: https://thepugs.tk
  - name: Vaultwarden
    url: https://pass.abhishekakt.tk
  - name: MQTT
    url: mqtt.abhishekakt.tk
    port: 1833
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime Monitor"
  introMessage: 
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
